### ISSUE TITLE
expires_date and purchase_date returned as same day?

### ISSUE THREAD

**Issue by booboothefool** [sibelius/iap-receipt-validator#12]
(testing in sandbox)

![screen shot 2017-04-18 at 6 06 23 am](https://cloud.githubusercontent.com/assets/13257645/25125554/3e7e582c-23fd-11e7-9450-5cbe3f9c4bea.png)

I would expect the `expires_date` to be 2017-05-18 for this subscription that is to auto-renew every month.

**Comment by booboothefool** [comment]
https://github.com/sibelius/iap-receipt-validator/issues/10

**Comment by ObidosDev** [comment]
@booboothefool I guess that you used the sandbox where subscriptions expires in 5 minutes (for month)!!! if you just calculate the ms or look onto time you will see difference :)
