### ISSUE TITLE
Publish the latest version via npm

### ISSUE THREAD

**Issue by ghsdh3409** [sibelius/iap-receipt-validator#16]
I checked that there are some changes to handle status code `21006` that says `Receipt valid but sub expired`.

Current version on the npm (v1.0.6) still considers this status code as an error.
Please publish the latest version via npm.

Thanks for your efforts :)

**Comment by ghsdh3409** [comment]
@ohtangza

**Comment by raduflp** [comment]
would love to see the latest changes published as well

**Comment by sibelius** [comment]
done https://www.npmjs.com/package/iap-receipt-validator

**Comment by Damnum** [comment]
@sibelius latest version on npm is still 1.0.6 from 2016-12-23
