### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by skilesare** [sibelius/iap-receipt-validator#4]
I'm running into this issue when I try to use this module.

```
    @iapReceiptValidator = require( 'iap-receipt-validator')
    password = 'xxxxxxxxxx' # Shared Secret from iTunes connect
    production = req.body.production # use sandbox or production url for validation
    validateReceipt = @iapReceiptValidator.default(password, production)
```

It fails on the last line.  The furthest it gets is line 18 in index.js in the dbugger
```
var _ref = _asyncToGenerator(regeneratorRuntime.mark(function _callee(receipt) {
```

**Comment by skilesare** [comment]
I fixed it by adding babel to my project and requiring babel-polyfill.

Perhaps you should do this inside the module?
```
if(!regeneratorRuntime){
require('babel-polyfill');
}

**Comment by skilesare** [comment]
Also an issue is that fetch is assumed.  I'm sending the receipt data to a server so that my password is not built into the app.(seem like a sensible security measure).  My express server doesn't have these polyfills by default.

**Comment by sibelius** [comment]
could u send a PR to fix this issue?

just add `import 'babel-polyfill';` on top of this file: https://github.com/sibelius/iap-receipt-validator/blob/master/src/index.js#L1

also, about fetch, could you please add an `if` to test with fetch exist and if not throw an error or a warning
