### ISSUE TITLE
Function should return body and not receipt

### ISSUE THREAD

**Issue by EdmundMai** [sibelius/iap-receipt-validator#7]
Currently it's just returning whatever you receipt you pass the function. I think it should be returning the response from apple:

https://github.com/sibelius/iap-receipt-validator/blob/master/src/index.js#L60

should be

`return body;`

**Comment by sibelius** [comment]
That's true, could u send a PR to fix this?

**Comment by EdmundMai** [comment]
https://github.com/sibelius/iap-receipt-validator/pull/8

**Comment by sibelius** [comment]
fixed here: https://github.com/sibelius/iap-receipt-validator/pull/8

tks
